### ISSUE TITLE
Doesn't Support Authenticated Commands

### ISSUE THREAD

**Issue by timnolte** [vetruvet/laravel-phpredis#11]
Our Redis instances require authentication in order to issue commands. It doesn't appear that this PhpRedis implementation supports that.

**Comment by timnolte** [comment]
I'm investigating this right now. This may not be an issue, but on the surface it didn't seem as though it was supporting the `auth` call.

**Comment by timnolte** [comment]
This has been fixed in the submitted PR #12

**Comment by timnolte** [comment]
@vetruvet Can you create a new release Tag for the latest master that includes this PR #12 ? Thanks!

**Comment by vetruvet** [comment]
Good call, thanks for the PR!
