### ISSUE TITLE
L 5.1 issue?

### ISSUE THREAD

**Issue by nardev** [vetruvet/laravel-phpredis#3]
Any idea how to fix this???

ErrorException in Database.php line 8:
Declaration of Vetruvet\PhpRedis\Database::createAggregateClient() should be compatible with Illuminate\Redis\Database::createAggregateClient(array $servers, array $options = Array)

**Comment by nardev** [comment]
At the end, it was fixed.

Adding ", array $options = []" as a second parameter in two methods of class Database

PhpRedis\Database.php

protected function createAggregateClient(array $servers, array $options = [])

protected function createSingleClients(array $servers, array $options = [])

hint from: @christophelimpalair

p.s. Please update this changes ASP so that i can do composer update relaxed :dash:

**Comment by vetruvet** [comment]
Thanks for the fix! Tagged in version 1.0.2.

**Comment by vrga** [comment]
Your fix has not been picked up by packagist, and released version is stil 1.0.0.
Please remove the version tag from your composer.json :)
https://github.com/composer/packagist/issues/434

**Comment by vetruvet** [comment]
Thanks @vrga . version removed from composer.json now
