### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by it-can** [vetruvet/laravel-phpredis#4]
Does this package completely override Predis? Or do I need Predis installed? I am asking because I want my queue to use phpredis and not predis (performance reasons)...
Thanks!

**Comment by vetruvet** [comment]
No, you can have Predis alongside or not have it at all. Predis is all namespaced so just make sure you're referencing the correct class.

**Comment by it-can** [comment]
Ok, but if I install your package, will the queue also use this package?

**Comment by vetruvet** [comment]
Yes, the Redis queue connector in Laravel will use the the configured connector.
