### ISSUE TITLE
Any Plans For Working it Out For Laravel 5.2?

### ISSUE THREAD

**Issue by masterpowers** [vetruvet/laravel-phpredis#6]
Hi Ive tried your package in 5.1 it works, but would love to see it also in 5.2 thanks

**Comment by bernier** [comment]
Same here.
There was no update within the past 6 months. Is there another library I can use?

**Comment by vetruvet** [comment]
I've been really busy and actually haven't used this myself lately, thus the lack of updates. I'm going to try to get this updated this week for 5.2, no promises though ;-)

**Comment by bernier** [comment]
Thanks!

**Comment by vetruvet** [comment]
Fixed in v1.0.3
